package GUI;

import javax.swing.JPanel;
import javax.swing.JButton;
import java.awt.Graphics;
import Structure.*;
import java.util.*;

/**
 *
 * @author stoicneutron
 */
public class GraphSandboxUI extends javax.swing.JFrame {
    
    // Global Variable
    public Graphics g;
    public JButton[] jButton_nodeslist;
    public Graph graphNode;

    /**
     * Constructor
     */
    public GraphSandboxUI() {
        
        initComponents();
        
        g = jPanel2.getGraphics();
        jPanel2.paintComponents(g);
        
        JButton[] tempButtonNodeList = {nf4, ne4, ne5, nf5, ng5, ng4, ne3, nf3, nd3, nd4, nd5, nd6, ne6, nf6, ng6, nh6, nh5, nh4, nh3, nh2, ng2, nf2, ne2, nd2, nc2, nc3, nc4, nc5, nc6, nc7, nd7, ne7, nf7, ng7, nh7, ni7, ni6, ni5, ni4, ni3, ni2, ni1, nh1, ng1, nf1, ne1, nd1, nc1, nb1, nb2, nb3, nb4, nb5, nb6, nb7, nj7, nj6, nj5, nj4, nj3, nj2, nj1, na1, na2, na3, na4, na5, na6, na7};
        this.jButton_nodeslist = tempButtonNodeList;
        
        graphNode = new Graph();
        
        // Store the Jbuttons list from GUI to the Graph structure
        for(int i = 0; i < tempButtonNodeList.length; i++){
            
            Node node = new Node(tempButtonNodeList[i]);
            graphNode.graph.add(node);
        }
        graphNode.totalNodes = graphNode.graph.size();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPanel2 = new javax.swing.JPanel();
        na1 = new MyButton();
        na2 = new MyButton();
        na3 = new MyButton();
        na4 = new MyButton();
        na5 = new MyButton();
        na6 = new MyButton();
        na7 = new MyButton();
        nb1 = new MyButton();
        nc1 = new MyButton();
        nd1 = new MyButton();
        ne1 = new MyButton();
        nf1 = new MyButton();
        ng1 = new MyButton();
        nh1 = new MyButton();
        ni1 = new MyButton();
        nj1 = new MyButton();
        nc2 = new MyButton();
        nd2 = new MyButton();
        ne2 = new MyButton();
        nf2 = new MyButton();
        ng2 = new MyButton();
        nh2 = new MyButton();
        ni2 = new MyButton();
        nj2 = new MyButton();
        nb2 = new MyButton();
        nf3 = new MyButton();
        ng3 = new MyButton();
        nh3 = new MyButton();
        ni3 = new MyButton();
        nj3 = new MyButton();
        nb3 = new MyButton();
        nc3 = new MyButton();
        nd3 = new MyButton();
        ne3 = new MyButton();
        nh4 = new MyButton();
        nf4 = new MyButton();
        ng4 = new MyButton();
        nb4 = new MyButton();
        nc4 = new MyButton();
        ne4 = new MyButton();
        nj4 = new MyButton();
        nd4 = new MyButton();
        ni4 = new MyButton();
        ne5 = new MyButton();
        nb5 = new MyButton();
        nc5 = new MyButton();
        nf5 = new MyButton();
        ng5 = new MyButton();
        nh5 = new MyButton();
        nj5 = new MyButton();
        ni5 = new MyButton();
        nd5 = new MyButton();
        ng6 = new MyButton();
        nd6 = new MyButton();
        nj6 = new MyButton();
        nh6 = new MyButton();
        nf6 = new MyButton();
        ne6 = new MyButton();
        nb6 = new MyButton();
        nc6 = new MyButton();
        ni6 = new MyButton();
        nf7 = new MyButton();
        nb7 = new MyButton();
        nh7 = new MyButton();
        ng7 = new MyButton();
        nd7 = new MyButton();
        ni7 = new MyButton();
        nc7 = new MyButton();
        nj7 = new MyButton();
        ne7 = new MyButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        size_input = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        complete_Button = new javax.swing.JRadioButton();
        random_Button = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        weighted_Button = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        directed_Button = new javax.swing.JToggleButton();
        construct_Button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        vertexID = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graph_Sandbox");
        setMinimumSize(new java.awt.Dimension(1000, 750));
        setName("mainFrame"); // NOI18N
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 0));

        na1.setText("A1");
        na1.setPreferredSize(new java.awt.Dimension(50, 50));
        na1.setSize(new java.awt.Dimension(50, 50));
        na1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                na1ActionPerformed(evt);
            }
        });

        na2.setText("A2");
        na2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                na2ActionPerformed(evt);
            }
        });

        na3.setText("A3");
        na3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                na3ActionPerformed(evt);
            }
        });

        na4.setText("A4");
        na4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                na4ActionPerformed(evt);
            }
        });

        na5.setText("A5");
        na5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                na5ActionPerformed(evt);
            }
        });

        na6.setText("A6");
        na6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                na6ActionPerformed(evt);
            }
        });

        na7.setText("A7");
        na7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                na7ActionPerformed(evt);
            }
        });

        nb1.setText("B1");
        nb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nb1ActionPerformed(evt);
            }
        });

        nc1.setText("C1");
        nc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nc1ActionPerformed(evt);
            }
        });

        nd1.setText("D1");
        nd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nd1ActionPerformed(evt);
            }
        });

        ne1.setText("E1");
        ne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ne1ActionPerformed(evt);
            }
        });

        nf1.setText("F1");
        nf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf1ActionPerformed(evt);
            }
        });

        ng1.setText("G1");
        ng1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ng1ActionPerformed(evt);
            }
        });

        nh1.setText("H1");
        nh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nh1ActionPerformed(evt);
            }
        });

        ni1.setText("I1");
        ni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ni1ActionPerformed(evt);
            }
        });

        nj1.setText("J1");
        nj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nj1ActionPerformed(evt);
            }
        });

        nc2.setText("C2");
        nc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nc2ActionPerformed(evt);
            }
        });

        nd2.setText("D2");
        nd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nd2ActionPerformed(evt);
            }
        });

        ne2.setText("E2");
        ne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ne2ActionPerformed(evt);
            }
        });

        nf2.setText("F2");
        nf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf2ActionPerformed(evt);
            }
        });

        ng2.setText("G2");
        ng2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ng2ActionPerformed(evt);
            }
        });

        nh2.setText("H2");
        nh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nh2ActionPerformed(evt);
            }
        });

        ni2.setText("I2");
        ni2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ni2ActionPerformed(evt);
            }
        });

        nj2.setText("J2");
        nj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nj2ActionPerformed(evt);
            }
        });

        nb2.setText("B2");
        nb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nb2ActionPerformed(evt);
            }
        });

        nf3.setText("F3");
        nf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf3ActionPerformed(evt);
            }
        });

        ng3.setText("G3");
        ng3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ng3ActionPerformed(evt);
            }
        });

        nh3.setText("H3");
        nh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nh3ActionPerformed(evt);
            }
        });

        ni3.setText("I3");
        ni3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ni3ActionPerformed(evt);
            }
        });

        nj3.setText("J3");
        nj3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nj3ActionPerformed(evt);
            }
        });

        nb3.setText("B3");
        nb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nb3ActionPerformed(evt);
            }
        });

        nc3.setText("C3");
        nc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nc3ActionPerformed(evt);
            }
        });

        nd3.setText("D3");
        nd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nd3ActionPerformed(evt);
            }
        });

        ne3.setText("E3");
        ne3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ne3ActionPerformed(evt);
            }
        });

        nh4.setText("H4");
        nh4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nh4ActionPerformed(evt);
            }
        });

        nf4.setText("F4");
        nf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf4ActionPerformed(evt);
            }
        });

        ng4.setText("G4");
        ng4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ng4ActionPerformed(evt);
            }
        });

        nb4.setText("B4");
        nb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nb4ActionPerformed(evt);
            }
        });

        nc4.setText("C4");
        nc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nc4ActionPerformed(evt);
            }
        });

        ne4.setText("E4");
        ne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ne4ActionPerformed(evt);
            }
        });

        nj4.setText("J4");
        nj4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nj4ActionPerformed(evt);
            }
        });

        nd4.setText("D4");
        nd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nd4ActionPerformed(evt);
            }
        });

        ni4.setText("I4");
        ni4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ni4ActionPerformed(evt);
            }
        });

        ne5.setText("E5");
        ne5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ne5ActionPerformed(evt);
            }
        });

        nb5.setText("B5");
        nb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nb5ActionPerformed(evt);
            }
        });

        nc5.setText("C5");
        nc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nc5ActionPerformed(evt);
            }
        });

        nf5.setText("F5");
        nf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf5ActionPerformed(evt);
            }
        });

        ng5.setText("G5");
        ng5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ng5ActionPerformed(evt);
            }
        });

        nh5.setText("H5");
        nh5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nh5ActionPerformed(evt);
            }
        });

        nj5.setText("J5");
        nj5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nj5ActionPerformed(evt);
            }
        });

        ni5.setText("I5");
        ni5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ni5ActionPerformed(evt);
            }
        });

        nd5.setText("D5");
        nd5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nd5ActionPerformed(evt);
            }
        });

        ng6.setText("G6");
        ng6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ng6ActionPerformed(evt);
            }
        });

        nd6.setText("D6");
        nd6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nd6ActionPerformed(evt);
            }
        });

        nj6.setText("J6");
        nj6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nj6ActionPerformed(evt);
            }
        });

        nh6.setText("H6");
        nh6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nh6ActionPerformed(evt);
            }
        });

        nf6.setText("F6");
        nf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf6ActionPerformed(evt);
            }
        });

        ne6.setText("E6");
        ne6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ne6ActionPerformed(evt);
            }
        });

        nb6.setText("B6");
        nb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nb6ActionPerformed(evt);
            }
        });

        nc6.setText("C6");
        nc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nc6ActionPerformed(evt);
            }
        });

        ni6.setText("I6");
        ni6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ni6ActionPerformed(evt);
            }
        });

        nf7.setText("F7");
        nf7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf7ActionPerformed(evt);
            }
        });

        nb7.setText("B7");
        nb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nb7ActionPerformed(evt);
            }
        });

        nh7.setText("H7");
        nh7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nh7ActionPerformed(evt);
            }
        });

        ng7.setText("G7");
        ng7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ng7ActionPerformed(evt);
            }
        });

        nd7.setText("D7");
        nd7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nd7ActionPerformed(evt);
            }
        });

        ni7.setText("I7");
        ni7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ni7ActionPerformed(evt);
            }
        });

        nc7.setText("C7");
        nc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nc7ActionPerformed(evt);
            }
        });

        nj7.setText("J7");
        nj7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nj7ActionPerformed(evt);
            }
        });

        ne7.setText("E7");
        ne7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ne7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(na1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(na2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(na3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(na4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(na5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(na6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(na7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nb1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nc1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nd1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ne1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nf1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ng1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nh1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ni1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nj1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nc2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nd2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ne2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nf2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ng2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nh2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ni2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nj2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nb2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nf3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ng3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nh3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ni3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nj3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nb3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nc3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nd3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ne3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nh4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nf4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ng4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nb4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nc4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ne4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nj4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nd4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ni4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ne5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nb5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nc5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nf5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ng5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nh5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nj5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ni5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nd5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ng6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nd6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nj6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nh6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nf6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ne6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nb6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nc6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ni6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nf7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nb7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nh7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ng7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nd7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ni7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nc7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nj7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ne7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(na1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(na2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(na3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(na4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(na5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(na6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(na7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nb1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nc1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nd1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ne1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nf1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ng1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nh1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ni1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nj1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nb2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nc2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nd2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ne2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nf2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ng2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nh2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ni2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nj2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nb3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nc3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nd3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ne3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nf3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ng3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nh3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ni3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nj3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nb4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nc4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nd4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ne4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nf4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ng4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nh4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ni4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nj4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nb5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nc5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nd5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ne5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nf5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ng5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nh5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ni5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nj5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nb6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nc6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nd6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ne6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nf6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ng6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nh6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ni6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nj6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nb7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nc7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nd7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ne7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nf7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ng7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nh7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ni7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nj7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 209, 211));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Graph Sandbox", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Noteworthy", 1, 18))); // NOI18N

        jButton1.setText("RUN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Step 1: Construct your graph.");

        jLabel2.setText("Size:");

        size_input.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        size_input.setText("70");

        jLabel3.setText("(2-70)");

        jLabel4.setText("Connection:");

        complete_Button.setSelected(true);
        complete_Button.setText("Complete");
        complete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complete_ButtonActionPerformed(evt);
            }
        });

        random_Button.setText("Random");
        random_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                random_ButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Weighted:");

        weighted_Button.setText("False");
        weighted_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weighted_ButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Directed:");

        directed_Button.setText("False");
        directed_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directed_ButtonActionPerformed(evt);
            }
        });

        construct_Button.setText("Construct Graph");
        construct_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                construct_ButtonActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Step 2: Choose your algorithm, starting and ending node.");

        jLabel8.setText("Algorithm:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Starting Node:");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setText("E9");

        jLabel11.setText("Ending Node:");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setText("D9");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Node Properties"));

        jLabel13.setText("Vertex ID:");

        vertexID.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        vertexID.setText("E8");

        jButton3.setText("Set as Starting Node");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Set as Ending Node");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel15.setText("Total Edges:");

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel16.setText("4");

        jLabel17.setText("Adjacencies:");

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel18.setText("F9, D9, E8");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vertexID)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(vertexID)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jButton1)
                                .addContainerGap(29, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(weighted_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(directed_Button)
                                .addGap(31, 31, 31)
                                .addComponent(construct_Button))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(size_input, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(complete_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(random_Button))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(size_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(complete_Button)
                    .addComponent(random_Button))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(weighted_Button)
                    .addComponent(jLabel6)
                    .addComponent(directed_Button)
                    .addComponent(construct_Button))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getjPanel2() {
        return jPanel2;
    }
    
    public void drawEdges(){
        
        for(int i = 0; i < graphNode.totalNodes; i++){
            g.drawLine(graphNode.graph.get(i).xCoordinate, graphNode.graph.get(i).yCoordinate, graphNode.graph.get(i).xCoordinate, graphNode.graph.get(i).yCoordinate - 50);
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        drawEdges();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void complete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complete_ButtonActionPerformed
        // TODO add your handling code here:
        if(complete_Button.isSelected()){
            random_Button.setSelected(false);
        }else{
            random_Button.setSelected(true);
        }
    }//GEN-LAST:event_complete_ButtonActionPerformed

    private void random_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_random_ButtonActionPerformed
        // TODO add your handling code here:
        if(random_Button.isSelected()){
            complete_Button.setSelected(false);
        }else{
            complete_Button.setSelected(true);
        }
    }//GEN-LAST:event_random_ButtonActionPerformed

    private void weighted_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weighted_ButtonActionPerformed
        // TODO add your handling code here:
        if(weighted_Button.getText().equalsIgnoreCase("false")){
            weighted_Button.setText("True");
        }else{
            weighted_Button.setText("False");
        }
    }//GEN-LAST:event_weighted_ButtonActionPerformed

    private void construct_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_construct_ButtonActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_construct_ButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void na1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_na1ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("A1");
    }//GEN-LAST:event_na1ActionPerformed

    private void na2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_na2ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("A2");
    }//GEN-LAST:event_na2ActionPerformed

    private void na3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_na3ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("A3");
    }//GEN-LAST:event_na3ActionPerformed

    private void na4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_na4ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("A4");
    }//GEN-LAST:event_na4ActionPerformed

    private void na5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_na5ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("A5");
    }//GEN-LAST:event_na5ActionPerformed

    private void na6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_na6ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("A6");
    }//GEN-LAST:event_na6ActionPerformed

    private void na7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_na7ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("A7");
    }//GEN-LAST:event_na7ActionPerformed

    private void nb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nb1ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("B1");
    }//GEN-LAST:event_nb1ActionPerformed

    private void nb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nb2ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("B2");
    }//GEN-LAST:event_nb2ActionPerformed

    private void nb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nb3ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("B3");
    }//GEN-LAST:event_nb3ActionPerformed

    private void nb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nb4ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("B4");
    }//GEN-LAST:event_nb4ActionPerformed

    private void nb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nb5ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("B5");
    }//GEN-LAST:event_nb5ActionPerformed

    private void nb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nb6ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("B6");
    }//GEN-LAST:event_nb6ActionPerformed

    private void nb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nb7ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("B7");
    }//GEN-LAST:event_nb7ActionPerformed

    private void nc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nc1ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("C1");
    }//GEN-LAST:event_nc1ActionPerformed

    private void nc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nc2ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("C2");
    }//GEN-LAST:event_nc2ActionPerformed

    private void nc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nc3ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("C3");
    }//GEN-LAST:event_nc3ActionPerformed

    private void nc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nc4ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("C4");
    }//GEN-LAST:event_nc4ActionPerformed

    private void nc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nc5ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("C5");
    }//GEN-LAST:event_nc5ActionPerformed

    private void nc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nc6ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("C6");
    }//GEN-LAST:event_nc6ActionPerformed

    private void nc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nc7ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("C7");
    }//GEN-LAST:event_nc7ActionPerformed

    private void nd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nd1ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("D1");
    }//GEN-LAST:event_nd1ActionPerformed

    private void nd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nd2ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("D2");
    }//GEN-LAST:event_nd2ActionPerformed

    private void nd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nd3ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("D3");
    }//GEN-LAST:event_nd3ActionPerformed

    private void nd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nd4ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("D4");
    }//GEN-LAST:event_nd4ActionPerformed

    private void nd5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nd5ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("D5");
    }//GEN-LAST:event_nd5ActionPerformed

    private void nd6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nd6ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("D6");
    }//GEN-LAST:event_nd6ActionPerformed

    private void nd7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nd7ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("D7");
    }//GEN-LAST:event_nd7ActionPerformed

    private void ne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ne1ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("E1");
    }//GEN-LAST:event_ne1ActionPerformed

    private void ne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ne2ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("E2");
    }//GEN-LAST:event_ne2ActionPerformed

    private void ne3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ne3ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("E3");
    }//GEN-LAST:event_ne3ActionPerformed

    private void ne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ne4ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("E4");
    }//GEN-LAST:event_ne4ActionPerformed

    private void ne5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ne5ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("E5");
    }//GEN-LAST:event_ne5ActionPerformed

    private void ne6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ne6ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("E6");
    }//GEN-LAST:event_ne6ActionPerformed

    private void ne7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ne7ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("E7");
    }//GEN-LAST:event_ne7ActionPerformed

    private void nf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf1ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("F1");
    }//GEN-LAST:event_nf1ActionPerformed

    private void nf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf2ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("F2");
    }//GEN-LAST:event_nf2ActionPerformed

    private void nf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf3ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("F3");
    }//GEN-LAST:event_nf3ActionPerformed

    private void nf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf4ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("F4");
    }//GEN-LAST:event_nf4ActionPerformed

    private void nf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf5ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("F5");
    }//GEN-LAST:event_nf5ActionPerformed

    private void nf6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf6ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("F6");
    }//GEN-LAST:event_nf6ActionPerformed

    private void nf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf7ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("F7");
    }//GEN-LAST:event_nf7ActionPerformed

    private void ng1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ng1ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("G1");
    }//GEN-LAST:event_ng1ActionPerformed

    private void ng2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ng2ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("G2");
    }//GEN-LAST:event_ng2ActionPerformed

    private void ng3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ng3ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("G3");
    }//GEN-LAST:event_ng3ActionPerformed

    private void ng4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ng4ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("G4");
    }//GEN-LAST:event_ng4ActionPerformed

    private void ng5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ng5ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("G5");
    }//GEN-LAST:event_ng5ActionPerformed

    private void ng6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ng6ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("G6");
    }//GEN-LAST:event_ng6ActionPerformed

    private void ng7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ng7ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("G7");
    }//GEN-LAST:event_ng7ActionPerformed

    private void nh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nh1ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("H1");
    }//GEN-LAST:event_nh1ActionPerformed

    private void nh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nh2ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("H2");
    }//GEN-LAST:event_nh2ActionPerformed

    private void nh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nh3ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("H3");
    }//GEN-LAST:event_nh3ActionPerformed

    private void nh4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nh4ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("H4");
    }//GEN-LAST:event_nh4ActionPerformed

    private void nh5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nh5ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("H5");
    }//GEN-LAST:event_nh5ActionPerformed

    private void nh6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nh6ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("H6");
    }//GEN-LAST:event_nh6ActionPerformed

    private void nh7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nh7ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("H7");
    }//GEN-LAST:event_nh7ActionPerformed

    private void ni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ni1ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("I1");
    }//GEN-LAST:event_ni1ActionPerformed

    private void ni2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ni2ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("I2");
    }//GEN-LAST:event_ni2ActionPerformed

    private void ni3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ni3ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("I3");
    }//GEN-LAST:event_ni3ActionPerformed

    private void ni4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ni4ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("I4");
    }//GEN-LAST:event_ni4ActionPerformed

    private void ni5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ni5ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("I5");
    }//GEN-LAST:event_ni5ActionPerformed

    private void ni6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ni6ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("I6");
    }//GEN-LAST:event_ni6ActionPerformed

    private void ni7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ni7ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("I7");
    }//GEN-LAST:event_ni7ActionPerformed

    private void nj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nj1ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("J1");
    }//GEN-LAST:event_nj1ActionPerformed

    private void nj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nj2ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("J2");
    }//GEN-LAST:event_nj2ActionPerformed

    private void nj3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nj3ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("J3");
    }//GEN-LAST:event_nj3ActionPerformed

    private void nj4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nj4ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("J4");
    }//GEN-LAST:event_nj4ActionPerformed

    private void nj5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nj5ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("J5");
    }//GEN-LAST:event_nj5ActionPerformed

    private void nj6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nj6ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("J6");
    }//GEN-LAST:event_nj6ActionPerformed

    private void nj7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nj7ActionPerformed
        // TODO add your handling code here:
        vertexID.setText("J7");
    }//GEN-LAST:event_nj7ActionPerformed

    private void directed_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directed_ButtonActionPerformed
        // TODO add your handling code here:
        if(directed_Button.getText().equalsIgnoreCase("false")){
            directed_Button.setText("True");
        }else{
            directed_Button.setText("False");
        }
    }//GEN-LAST:event_directed_ButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton complete_Button;
    private javax.swing.JButton construct_Button;
    private javax.swing.JToggleButton directed_Button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton na1;
    private javax.swing.JButton na2;
    private javax.swing.JButton na3;
    private javax.swing.JButton na4;
    private javax.swing.JButton na5;
    private javax.swing.JButton na6;
    private javax.swing.JButton na7;
    private javax.swing.JButton nb1;
    private javax.swing.JButton nb2;
    private javax.swing.JButton nb3;
    private javax.swing.JButton nb4;
    private javax.swing.JButton nb5;
    private javax.swing.JButton nb6;
    private javax.swing.JButton nb7;
    private javax.swing.JButton nc1;
    private javax.swing.JButton nc2;
    private javax.swing.JButton nc3;
    private javax.swing.JButton nc4;
    private javax.swing.JButton nc5;
    private javax.swing.JButton nc6;
    private javax.swing.JButton nc7;
    private javax.swing.JButton nd1;
    private javax.swing.JButton nd2;
    private javax.swing.JButton nd3;
    private javax.swing.JButton nd4;
    private javax.swing.JButton nd5;
    private javax.swing.JButton nd6;
    private javax.swing.JButton nd7;
    private javax.swing.JButton ne1;
    private javax.swing.JButton ne2;
    private javax.swing.JButton ne3;
    private javax.swing.JButton ne4;
    private javax.swing.JButton ne5;
    private javax.swing.JButton ne6;
    private javax.swing.JButton ne7;
    private javax.swing.JButton nf1;
    private javax.swing.JButton nf2;
    private javax.swing.JButton nf3;
    private javax.swing.JButton nf4;
    private javax.swing.JButton nf5;
    private javax.swing.JButton nf6;
    private javax.swing.JButton nf7;
    private javax.swing.JButton ng1;
    private javax.swing.JButton ng2;
    private javax.swing.JButton ng3;
    private javax.swing.JButton ng4;
    private javax.swing.JButton ng5;
    private javax.swing.JButton ng6;
    private javax.swing.JButton ng7;
    private javax.swing.JButton nh1;
    private javax.swing.JButton nh2;
    private javax.swing.JButton nh3;
    private javax.swing.JButton nh4;
    private javax.swing.JButton nh5;
    private javax.swing.JButton nh6;
    private javax.swing.JButton nh7;
    private javax.swing.JButton ni1;
    private javax.swing.JButton ni2;
    private javax.swing.JButton ni3;
    private javax.swing.JButton ni4;
    private javax.swing.JButton ni5;
    private javax.swing.JButton ni6;
    private javax.swing.JButton ni7;
    private javax.swing.JButton nj1;
    private javax.swing.JButton nj2;
    private javax.swing.JButton nj3;
    private javax.swing.JButton nj4;
    private javax.swing.JButton nj5;
    private javax.swing.JButton nj6;
    private javax.swing.JButton nj7;
    private javax.swing.JRadioButton random_Button;
    private javax.swing.JTextField size_input;
    private javax.swing.JLabel vertexID;
    private javax.swing.JToggleButton weighted_Button;
    // End of variables declaration//GEN-END:variables

}
